# Generated by Django 3.1.6 on 2021-02-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('est_date', models.DateTimeField(verbose_name='date published')),
                ('open_close', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('est_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoomRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareToDo.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareToDo.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_room',
            field=models.ManyToManyField(through='shareToDo.UserRoomRelation', to='shareToDo.Room'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareToDo.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareToDo.category')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareToDo.room')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareToDo.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareToDo.user')),
            ],
        ),
    ]
