# Generated by Django 3.1.6 on 2021-02-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareToDo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='est_date',
        ),
    ]
